<?php

namespace Database\Seeders;

use App\Models\ClientVerification;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        $email = config('seed_accounts.client_email');
        $password = config('seed_accounts.client_password');

        if (! $email || ! $password) {
            return;
        }

        $client = User::query()->firstOrNew(['email' => $email]);

        $client->forceFill([
            'first_name' => 'Demo',
            'last_name' => 'Client',
            'name' => 'Demo Client',
            'password' => Hash::make($password),
            'role' => 'client',
            'email_verified_at' => now(),
            'contact_number' => 'Not provided',
            'age' => 18,
            'address' => 'Not provided',
        ])->save();

        $documentDirectory = 'client-verifications/'.$client->id;
        $validIdPath = $documentDirectory.'/seeded-valid-id.svg';
        $selfiePath = $documentDirectory.'/seeded-selfie.svg';

        Storage::disk('local')->put($validIdPath, $this->placeholderDocument('Seeded valid ID'));
        Storage::disk('local')->put($selfiePath, $this->placeholderDocument('Seeded selfie with ID'));

        $admin = User::query()
            ->where('email', config('seed_accounts.admin_email'))
            ->where('role', 'admin')
            ->first();

        ClientVerification::query()->updateOrCreate(
            ['user_id' => $client->id],
            [
                'status' => ClientVerification::STATUS_APPROVED,
                'employment_status' => 'employed',
                'company_name' => 'Inkcredible Test Company',
                'job_title' => 'Quality Assurance Tester',
                'monthly_income' => 25000,
                'employment_length_months' => 12,
                'source_of_income' => 'Employment salary',
                'valid_id_type' => 'Philippine National ID',
                'valid_id_number' => 'SEED-CLIENT-ID-0001',
                'valid_id_path' => $validIdPath,
                'selfie_with_id_path' => $selfiePath,
                'additional_information' => 'Approved test verification created by the client seeder.',
                'rejection_reason' => null,
                'submitted_at' => now(),
                'reviewed_at' => now(),
                'reviewed_by' => $admin?->id,
            ],
        );
    }

    private function placeholderDocument(string $label): string
    {
        $safeLabel = htmlspecialchars($label, ENT_QUOTES | ENT_XML1, 'UTF-8');

        return <<<SVG
            <svg xmlns="http://www.w3.org/2000/svg" width="900" height="560" viewBox="0 0 900 560">
                <rect width="900" height="560" fill="#f8fafc"/>
                <rect x="36" y="36" width="828" height="488" rx="24" fill="#ffffff" stroke="#cbd5e1" stroke-width="3"/>
                <circle cx="450" cy="224" r="72" fill="#e0e7ff"/>
                <path d="M420 224h60M450 194v60" stroke="#4f46e5" stroke-width="12" stroke-linecap="round"/>
                <text x="450" y="340" text-anchor="middle" font-family="Arial, sans-serif" font-size="30" font-weight="700" fill="#0f172a">{$safeLabel}</text>
                <text x="450" y="382" text-anchor="middle" font-family="Arial, sans-serif" font-size="20" fill="#64748b">Test document generated by ClientSeeder</text>
            </svg>
            SVG;
    }
}
