<?php

namespace App\Services;

use App\Models\Payment;
use RuntimeException;

class PaymentReceiptImage
{
    private const WIDTH = 720;

    private const HEIGHT = 1120;

    private string $regularFont;

    private string $boldFont;

    public function __construct()
    {
        $fontDirectory = base_path('vendor/dompdf/dompdf/lib/fonts');
        $this->regularFont = $fontDirectory.'/DejaVuSans.ttf';
        $this->boldFont = $fontDirectory.'/DejaVuSans-Bold.ttf';
    }

    public function render(Payment $payment): string
    {
        if (! extension_loaded('gd') || ! function_exists('imagepng')) {
            throw new RuntimeException('The GD extension is required to create payment receipt images.');
        }

        $image = imagecreatetruecolor(self::WIDTH, self::HEIGHT);

        if (! $image) {
            throw new RuntimeException('The payment receipt image could not be created.');
        }

        imageantialias($image, true);
        imagefill($image, 0, 0, $this->color($image, '#eef2f7'));

        $paper = $this->color($image, '#ffffff');
        $ink = $this->color($image, '#101828');
        $muted = $this->color($image, '#667085');
        $subtle = $this->color($image, '#98a2b3');
        $border = $this->color($image, '#e4e7ec');
        $primary = $this->color($image, '#4f46e5');

        $this->roundedRectangle($image, 42, 28, 678, 1090, 22, $paper);
        imagefilledrectangle($image, 42, 28, 678, 39, $primary);

        $this->text($image, 24, 74, 82, $primary, 'Inkcredible', true);
        $this->text($image, 10, 74, 111, $muted, 'OFFICIAL PAYMENT RECEIPT');
        $this->textRight($image, 11, 646, 85, $muted, 'RECEIPT #'.str_pad((string) $payment->id, 8, '0', STR_PAD_LEFT), true);

        $this->dashedLine($image, 74, 148, 646, $border);

        $status = strtoupper($payment->status);
        [$statusInk, $statusFill] = match ($payment->status) {
            Payment::STATUS_APPROVED => [$this->color($image, '#067647'), $this->color($image, '#ecfdf3')],
            Payment::STATUS_REJECTED => [$this->color($image, '#b42318'), $this->color($image, '#fef3f2')],
            default => [$this->color($image, '#b54708'), $this->color($image, '#fffaeb')],
        };

        $this->textCenter($image, 10, 360, 191, $muted, 'PAYMENT AMOUNT', true);
        $this->textCenter($image, 35, 360, 247, $ink, '₱'.number_format((float) $payment->amount, 2), true);
        $this->pill($image, 360, 287, $status, $statusInk, $statusFill);

        $date = ($payment->paid_at ?? $payment->created_at)?->copy()->timezone('Asia/Manila');
        $this->textCenter($image, 10, 360, 335, $muted, ($date?->format('M j, Y - g:i A') ?? 'Date unavailable').' PHT');

        $this->dashedLine($image, 74, 374, 646, $border);

        $loan = $payment->loan;
        $client = $loan?->user ?? $payment->user;
        $reference = $payment->provider_reference ?: $payment->reference ?: 'Payment #'.$payment->id;
        $loanCode = $loan?->loan_code ?: 'Loan #'.$payment->loan_id;
        $loanProduct = $loan?->loanType?->display_name ?? $loan?->loanType?->name ?? 'Loan';

        $rows = [
            ['Reference', $reference],
            ['Transaction ID', '#'.$payment->id],
            ['Client', $client?->name ?? 'Unknown client'],
            ['Loan account', $loanCode],
            ['Loan product', $loanProduct],
            ['Payment method', $payment->method_label],
        ];

        $y = 414;
        foreach ($rows as [$label, $value]) {
            $this->text($image, 9, 82, $y, $subtle, strtoupper($label), true);
            $this->textRight($image, 12, 638, $y + 1, $ink, $this->truncate($value, 38), true);
            imageline($image, 82, $y + 27, 638, $y + 27, $border);
            $y += 67;
        }

        $message = match ($payment->status) {
            Payment::STATUS_APPROVED => 'This payment was confirmed and applied to the associated loan account.',
            Payment::STATUS_PENDING => 'This payment is awaiting confirmation and is not proof of final settlement.',
            default => 'This payment was rejected. No amount was applied to the loan account.',
        };

        $notice = $this->color($image, '#f8f9ff');
        $this->roundedRectangle($image, 74, 826, 646, 908, 12, $notice);
        imagefilledrectangle($image, 74, 826, 79, 908, $primary);
        $this->wrappedText($image, 10, 96, 858, 520, 21, $muted, $message);

        $this->drawBarcode($image, 226, 944, 268, 54, $payment->reference ?: (string) $payment->id, $ink);
        $this->textCenter($image, 9, 360, 1022, $muted, $payment->reference ?: 'PAYMENT-'.$payment->id);
        $this->textCenter($image, 8, 360, 1061, $subtle, 'Generated by Inkcredible • '.now()->timezone('Asia/Manila')->format('M j, Y g:i A').' PHT');

        ob_start();
        imagepng($image, null, 9);
        $png = ob_get_clean();
        imagedestroy($image);

        if (! is_string($png)) {
            throw new RuntimeException('The payment receipt image could not be encoded.');
        }

        return $png;
    }

    private function color(\GdImage $image, string $hex): int
    {
        $hex = ltrim($hex, '#');

        return imagecolorallocate(
            $image,
            hexdec(substr($hex, 0, 2)),
            hexdec(substr($hex, 2, 2)),
            hexdec(substr($hex, 4, 2))
        );
    }

    private function roundedRectangle(\GdImage $image, int $x1, int $y1, int $x2, int $y2, int $radius, int $color): void
    {
        imagefilledrectangle($image, $x1 + $radius, $y1, $x2 - $radius, $y2, $color);
        imagefilledrectangle($image, $x1, $y1 + $radius, $x2, $y2 - $radius, $color);
        imagefilledellipse($image, $x1 + $radius, $y1 + $radius, $radius * 2, $radius * 2, $color);
        imagefilledellipse($image, $x2 - $radius, $y1 + $radius, $radius * 2, $radius * 2, $color);
        imagefilledellipse($image, $x1 + $radius, $y2 - $radius, $radius * 2, $radius * 2, $color);
        imagefilledellipse($image, $x2 - $radius, $y2 - $radius, $radius * 2, $radius * 2, $color);
    }

    private function text(\GdImage $image, int $size, int $x, int $y, int $color, string $text, bool $bold = false): void
    {
        imagettftext($image, $size, 0, $x, $y, $color, $bold ? $this->boldFont : $this->regularFont, $text);
    }

    private function textRight(\GdImage $image, int $size, int $right, int $y, int $color, string $text, bool $bold = false): void
    {
        $font = $bold ? $this->boldFont : $this->regularFont;
        $box = imagettfbbox($size, 0, $font, $text);
        $width = $box ? $box[2] - $box[0] : 0;
        imagettftext($image, $size, 0, $right - $width, $y, $color, $font, $text);
    }

    private function textCenter(\GdImage $image, int $size, int $center, int $y, int $color, string $text, bool $bold = false): void
    {
        $font = $bold ? $this->boldFont : $this->regularFont;
        $box = imagettfbbox($size, 0, $font, $text);
        $width = $box ? $box[2] - $box[0] : 0;
        imagettftext($image, $size, 0, $center - (int) ($width / 2), $y, $color, $font, $text);
    }

    private function wrappedText(\GdImage $image, int $size, int $x, int $y, int $maxWidth, int $lineHeight, int $color, string $text): void
    {
        $line = '';
        foreach (explode(' ', $text) as $word) {
            $candidate = trim($line.' '.$word);
            $box = imagettfbbox($size, 0, $this->regularFont, $candidate);
            $width = $box ? $box[2] - $box[0] : 0;

            if ($width > $maxWidth && $line !== '') {
                $this->text($image, $size, $x, $y, $color, $line);
                $line = $word;
                $y += $lineHeight;
            } else {
                $line = $candidate;
            }
        }

        if ($line !== '') {
            $this->text($image, $size, $x, $y, $color, $line);
        }
    }

    private function dashedLine(\GdImage $image, int $x1, int $y, int $x2, int $color): void
    {
        for ($x = $x1; $x < $x2; $x += 14) {
            imageline($image, $x, $y, min($x + 7, $x2), $y, $color);
        }
    }

    private function pill(\GdImage $image, int $center, int $y, string $text, int $textColor, int $fillColor): void
    {
        $box = imagettfbbox(10, 0, $this->boldFont, $text);
        $textWidth = $box ? $box[2] - $box[0] : 60;
        $width = $textWidth + 34;
        $this->roundedRectangle($image, $center - (int) ($width / 2), $y - 22, $center + (int) ($width / 2), $y + 10, 16, $fillColor);
        $this->textCenter($image, 10, $center, $y, $textColor, $text, true);
    }

    private function drawBarcode(\GdImage $image, int $x, int $y, int $width, int $height, string $seed, int $color): void
    {
        $bits = '';
        foreach (str_split(hash('sha256', $seed)) as $character) {
            $bits .= str_pad(base_convert($character, 16, 2), 4, '0', STR_PAD_LEFT);
        }

        $barWidth = max(1, (int) floor($width / strlen($bits)));
        foreach (str_split($bits) as $index => $bit) {
            if ($bit === '1') {
                imagefilledrectangle($image, $x + ($index * $barWidth), $y, $x + ($index * $barWidth) + $barWidth, $y + $height, $color);
            }
        }
    }

    private function truncate(string $value, int $limit): string
    {
        return mb_strlen($value) > $limit ? mb_substr($value, 0, $limit - 1).'…' : $value;
    }
}
