<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Loan Terms and Borrower Disclosure | Inkcredible</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>@include('partials.legal-styles')</style>
</head>
<body>
<header class="legal-header"><div class="header-inner"><a class="brand" href="{{ route('login') }}"><span class="brand-mark">I</span>Inkcredible</a><div class="eyebrow">Borrower disclosure</div><h1>Loan Terms and Conditions</h1><p class="header-description">Important information about approval, interest, repayment, penalties, lawful collection, privacy, and fraud reporting.</p></div></header>
<main class="legal-main"><article class="legal-card">
    <div class="legal-meta"><span>Version {{ config('legal.loan_terms_version') }}</span><span>Effective September 14, 2026</span></div>
    <div class="legal-notice"><strong>Read before applying:</strong> The product card and live estimate show the selected loan's current principal limits, interest rate, repayment term, and estimated total. Review them together with these terms before accepting.</div>

    <section class="section"><h2>1. Application and approval</h2><p>A submitted request is subject to identity, eligibility, document, and affordability review. Submission does not guarantee approval or disbursement. Information and documents must be accurate and authentic.</p></section>
    <section class="section"><h2>2. Principal, interest, and total repayment</h2><p>The requested principal, product interest rate, calculated interest, and estimated total repayment are shown before submission. The approved loan record and repayment schedule control the final obligation. Ask for clarification before accepting if any amount is unclear.</p></section>
    <section class="section"><h2>3. Due dates and payments</h2><p>You agree to pay the amounts due by the dates in the approved repayment schedule. Online payments are processed and verified through the configured payment provider. Cash submissions remain pending until proof is reviewed and approved. You should keep references and receipts and promptly report a payment discrepancy.</p></section>
    <section class="section"><h2>4. Penalties and charges</h2><p>If an approved balance becomes overdue, a late-payment penalty or other charge may be added only when its exact rate, fixed amount, basis, and timing have been disclosed in the approved loan or repayment schedule and the charge is permitted by applicable law. The dashboard must show any applied penalty as part of the balance.</p><ul><li>No undisclosed charge should be collected.</li><li>Interest and penalties are separate; the pre-submission estimate ordinarily shows product interest and excludes future late penalties.</li><li>A waived, reversed, or paid penalty should be reflected in the account record.</li></ul></section>
    <section class="section"><h2>5. Failure to pay and lawful collection</h2><p>Failure to pay on time may cause the account to become overdue, add properly disclosed lawful penalties, restrict access to additional borrowing, and lead to reminders, reasonable collection activity, or legally available civil remedies. Credit information may be furnished only to an authorized credit body when there is a lawful basis and applicable notice.</p><div class="highlight">Inkcredible and its representatives must not harass, threaten violence, publicly shame a borrower, contact unrelated persons, misuse personal data, or threaten action that cannot legally be taken.</div></section>
    <section class="section"><h2>6. Reports to authorities</h2><p>Suspected forged IDs, identity theft, deliberate payment fraud, falsified application information, unauthorized system access, or other potentially unlawful conduct may be documented and reported to appropriate law-enforcement agencies, regulators, payment providers, or other authorities when permitted or required by law.</p><p>Mere nonpayment or financial hardship is handled through lawful account servicing and collection processes and is not, by itself, represented in these terms as a criminal offense. Borrowers experiencing difficulty should seek assistance before the due date.</p></section>
    <section class="section"><h2>7. Privacy in loan processing and collection</h2><p>Personal information may be used only for necessary loan processing, servicing, payment, collection, fraud-prevention, support, and compliance purposes. Information must not be unnecessarily or disproportionately processed, and unrelated contacts must not be used to pressure payment.</p></section>
    <section class="section"><h2>8. Borrower acknowledgment</h2><p>By checking the acceptance box, you confirm that you reviewed the selected product's amount range, interest rate, repayment estimate and term; understand the possible consequences of late or missed payment; and agree that the acceptance date and terms version may be retained with the application.</p></section>

    <div class="legal-actions"><a class="button" href="{{ route('terms') }}">Account terms</a>@auth<a class="button button-primary" href="{{ route('loan.create') }}">Return to application</a>@else<a class="button button-primary" href="{{ route('register') }}">Create account</a>@endauth</div>
</article></main>
</body></html>
