<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Security Audit Logs | Inkcredible</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
@vite('resources/js/admin.js')
<style>
@include('partials.admin-styles')
.audit-summary { grid-template-columns:repeat(4,minmax(0,1fr)); }
.audit-summary .risk .stat-icon { color:#b42318; background:#fef3f2; }.audit-summary .privileged .stat-icon { color:#6941c6; background:#f4f3ff; }
.risk-banner { display:flex; align-items:center; justify-content:space-between; gap:18px; margin-bottom:18px; padding:15px 17px; color:#854a0e; background:#fffaeb; border:1px solid #fedf89; border-radius:12px; }
.risk-banner strong,.risk-banner span { display:block; }.risk-banner strong { font-size:12px; }.risk-banner span { margin-top:3px; font-size:10px; line-height:1.5; }.risk-badge { flex:0 0 auto; padding:7px 10px; color:#b42318; background:#fff; border:1px solid #fecdca; border-radius:999px; font-size:9px; font-weight:700; text-transform:uppercase; }
.audit-filter-panel { margin-bottom:20px; }.audit-filters { display:grid; grid-template-columns:minmax(220px,1.45fr) repeat(3,minmax(145px,.8fr)) repeat(2,minmax(135px,.7fr)); gap:11px; align-items:end; }
.filter-field { min-width:0; }.filter-field label { display:block; margin-bottom:6px; color:#475467; font-size:10px; font-weight:700; letter-spacing:.04em; text-transform:uppercase; }.filter-field .filter-select,.filter-field .search-input { width:100%; min-width:0; }.filter-actions { display:flex; justify-content:flex-end; gap:8px; margin-top:14px; }
.audit-table { table-layout:fixed; min-width:1040px; }.audit-table th:nth-child(1){width:13%}.audit-table th:nth-child(2){width:9%}.audit-table th:nth-child(3){width:18%}.audit-table th:nth-child(4){width:18%}.audit-table th:nth-child(5){width:25%}.audit-table th:nth-child(6){width:17%}.audit-table td { vertical-align:top; overflow-wrap:anywhere; }
.audit-primary { color:#1d2939; font-weight:600; line-height:1.45; }.audit-meta { margin-top:4px; color:#667085; font-size:10px; line-height:1.45; overflow-wrap:anywhere; }.severity { display:inline-flex; align-items:center; gap:6px; padding:5px 8px; border-radius:999px; font-size:9px; font-weight:700; text-transform:uppercase; }.severity::before { width:6px; height:6px; background:currentColor; border-radius:50%; content:''; }.severity-high{color:#b42318;background:#fef3f2}.severity-medium{color:#b54708;background:#fffaeb}.severity-info{color:#175cd3;background:#eff8ff}
.audit-action { display:inline-flex; max-width:100%; padding:5px 8px; color:#4338ca; background:#eef2ff; border-radius:7px; font-size:9px; font-weight:700; line-height:1.35; white-space:normal; }.event-details { margin-top:7px; }.event-details summary { color:#667085; cursor:pointer; font-size:9px; font-weight:600; }.event-details div { margin-top:6px; padding:7px 8px; color:#475467; background:#f8fafc; border-radius:7px; font-size:9px; line-height:1.5; }.audit-agent { display:-webkit-box; overflow:hidden; -webkit-box-orient:vertical; -webkit-line-clamp:2; }
.pagination-wrap { padding:16px 20px; border-top:1px solid #f2f4f7; }.pagination-wrap nav { display:flex; align-items:center; justify-content:space-between; gap:12px; flex-wrap:wrap; }.pagination-wrap svg { width:16px; height:16px; }
@media(max-width:1180px){.audit-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.audit-filters{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.audit-summary{grid-template-columns:1fr}.audit-filters{grid-template-columns:1fr 1fr}.audit-table{min-width:0;table-layout:auto}.audit-table thead{display:none}.audit-table,.audit-table tbody,.audit-table tr,.audit-table td{display:block;width:100%}.audit-table tbody{display:grid;gap:12px;padding:14px}.audit-table tr{padding:6px 16px;background:#fff;border:1px solid var(--border);border-radius:12px}.audit-table td{display:grid;grid-template-columns:110px minmax(0,1fr);gap:14px;padding:10px 0;border-bottom:1px solid #f2f4f7}.audit-table td:last-child{border-bottom:0}.audit-table td::before{color:#667085;content:attr(data-label);font-size:9px;font-weight:700;letter-spacing:.05em;text-transform:uppercase}}@media(max-width:560px){.audit-filters{grid-template-columns:1fr}.filter-actions{flex-direction:column}.filter-actions .button{width:100%}.risk-banner{align-items:flex-start;flex-direction:column}.audit-table td{grid-template-columns:1fr;gap:5px}}
</style>
</head>
<body>
@include('partials.admin-sidebar', ['active' => 'audit-logs'])
<main class="main" id="main-content" tabindex="-1"><div class="page-shell">
<header class="topbar"><div><div class="eyebrow">Superadmin security</div><h1>Security audit logs</h1><p class="subtitle">Investigate authentication, privileged access, and sensitive system activity in Philippine Time.</p></div><div class="top-actions"><a class="button button-secondary" href="{{ route('admin.security.dashboard') }}">Security dashboard</a></div></header>
<section class="stats-grid audit-summary" aria-label="Audit summary">
<article class="stat-card"><div class="stat-head"><span class="stat-label">Events today</span><span class="stat-icon"><svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M4 5h16v14H4zM8 3v4m8-4v4M4 9h16"/></svg></span></div><div class="stat-value">{{ number_format($summary['today']) }}</div><div class="stat-note">All recorded application events</div></article>
<article class="stat-card risk"><div class="stat-head"><span class="stat-label">Failed sign-ins</span><span class="stat-icon"><svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" stroke-width="1.8"/><path stroke-linecap="round" stroke-width="1.8" d="M12 8v5m0 3h.01"/></svg></span></div><div class="stat-value">{{ number_format($summary['failed_logins']) }}</div><div class="stat-note">During the last 24 hours</div></article>
<article class="stat-card"><div class="stat-head"><span class="stat-label">Failure source IPs</span><span class="stat-icon"><svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" stroke-width="1.8"/><path d="M3 12h18M12 3c2.5 2.5 3.7 5.5 3.7 9S14.5 18.5 12 21M12 3c-2.5 2.5-3.7 5.5-3.7 9s1.2 6.5 3.7 9" stroke-width="1.8"/></svg></span></div><div class="stat-value">{{ number_format($summary['source_ips']) }}</div><div class="stat-note">Distinct sources in 24 hours</div></article>
<article class="stat-card privileged"><div class="stat-head"><span class="stat-label">Privileged changes</span><span class="stat-icon"><svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M12 3.5 19 6v5c0 4.5-2.8 7.8-7 9.5C7.8 18.8 5 15.5 5 11V6zM9 12h6"/></svg></span></div><div class="stat-value">{{ number_format($summary['privileged_changes']) }}</div><div class="stat-note">Administrator changes in 7 days</div></article>
</section>
@if($summary['failed_logins'] > 0)<div class="risk-banner" role="status"><div><strong>Authentication activity needs review</strong><span>{{ $summary['failed_logins'] }} failed sign-in {{ Str::plural('attempt', $summary['failed_logins']) }} from {{ $summary['source_ips'] }} distinct {{ Str::plural('source', $summary['source_ips']) }} during the last 24 hours.</span></div><span class="risk-badge">Review high severity</span></div>@endif
<section class="panel audit-filter-panel"><div class="panel-header"><div><h2 class="panel-title">Investigate activity</h2><p class="panel-description">Search context and narrow events by severity, actor, action, or date.</p></div></div><div class="panel-body"><form method="GET" action="{{ route('admin.audit-logs.index') }}" data-async-filter data-async-filter-target="#audit-results" data-no-transition><div class="audit-filters">
<div class="filter-field"><label for="audit-q">Search</label><input class="search-input" id="audit-q" name="q" type="search" value="{{ $search }}" placeholder="Description, route, IP, name, or email"></div>
<div class="filter-field"><label for="severity">Severity</label><select class="filter-select" id="severity" name="severity"><option value="">All severities</option><option value="high" @selected(request('severity') === 'high')>High</option><option value="medium" @selected(request('severity') === 'medium')>Medium</option><option value="info" @selected(request('severity') === 'info')>Informational</option></select></div>
<div class="filter-field"><label for="user_id">Actor</label><select class="filter-select" id="user_id" name="user_id"><option value="">All actors</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)request('user_id') === (string)$user->id)>{{ $user->name }} - {{ $user->email }}</option>@endforeach</select></div>
<div class="filter-field"><label for="event_action">Action</label><select class="filter-select" id="event_action" name="event_action"><option value="">All actions</option>@foreach($actions as $action)<option value="{{ $action }}" @selected(request('event_action', request('action')) === $action)>{{ str($action)->replace('_',' ')->title() }}</option>@endforeach</select></div>
<div class="filter-field"><label for="date_from">From</label><input class="filter-select" type="date" id="date_from" name="date_from" value="{{ request('date_from') }}"></div><div class="filter-field"><label for="date_to">To</label><input class="filter-select" type="date" id="date_to" name="date_to" value="{{ request('date_to') }}"></div>
</div><div class="filter-actions"><a class="button button-secondary" href="{{ route('admin.audit-logs.index') }}" data-async-filter-link data-async-filter-target="#audit-results" data-no-transition>Clear filters</a><button class="button button-primary" type="submit">Apply filters</button></div></form></div></section>
<section class="panel async-filter-region" id="audit-results" data-async-filter-region data-async-filter-target="#audit-results" aria-live="polite"><div class="panel-header"><div><h2 class="panel-title">Recorded security activity</h2><p class="panel-description">{{ number_format($logs->total()) }} matching {{ Str::plural('event', $logs->total()) }}. Newest events appear first.</p></div></div>
@if($logs->isEmpty())<div class="empty-state"><strong>No audit activity found</strong>Try a wider date range or clear the filters.</div>@else<div class="table-wrap"><table class="audit-table"><thead><tr><th>Time (PHT)</th><th>Severity</th><th>Actor</th><th>Event</th><th>Context</th><th>Source</th></tr></thead><tbody>
@foreach($logs as $log)<tr><td data-label="Time (PHT)"><div class="audit-primary">{{ $log->occurred_at->timezone('Asia/Manila')->format('M d, Y') }}</div><div class="audit-meta">{{ $log->occurred_at->timezone('Asia/Manila')->format('h:i:s A') }}</div></td><td data-label="Severity"><span class="severity severity-{{ $log->severity }}">{{ $log->severity }}</span></td><td data-label="Actor"><div class="audit-primary">{{ $log->user?->name ?? 'Guest / deleted user' }}</div><div class="audit-meta">{{ $log->user?->email ?: 'Unauthenticated event' }}</div></td><td data-label="Event"><span class="audit-action">{{ str($log->action)->replace('_',' ')->title() }}</span><div class="audit-meta">{{ $log->method ?: 'SYSTEM' }} &middot; {{ $log->route ?: 'unnamed route' }}</div></td><td data-label="Context"><div class="audit-primary">{{ $log->description }}</div>@if($log->metadata)<details class="event-details"><summary>Technical context</summary><div>@if(data_get($log->metadata,'response_status'))HTTP status: {{ data_get($log->metadata,'response_status') }}<br>@endif @if(data_get($log->metadata,'email'))Account: {{ data_get($log->metadata,'email') }}<br>@endif @if(data_get($log->metadata,'route_parameters'))Resources: {{ collect(data_get($log->metadata,'route_parameters'))->map(fn($value,$key) => $key.'='.$value)->implode(', ') }}@endif</div></details>@endif</td><td data-label="Source"><div class="audit-primary">{{ $log->ip_address ?: 'Unknown IP' }}</div><div class="audit-meta audit-agent" title="{{ $log->user_agent }}">{{ $log->user_agent ?: 'User agent unavailable' }}</div></td></tr>@endforeach
</tbody></table></div>@if($logs->hasPages())<div class="pagination-wrap">{{ $logs->onEachSide(1)->links() }}</div>@endif @endif
</section></div></main>
</body></html>
